use salvo::prelude::*;
use crate::handlers;

pub fn create_router() -> Router {
    Router::new()
        .push(
            Router::with_path("api/v1")
                .push(
                    Router::with_path("health")
                        .get(handlers::health_check),
                )
                .push(
                    Router::with_path("auth")
                        .post(handlers::auth::login)
                        .push(
                            Router::with_path("logout")
                                .post(handlers::auth::logout),
                        )
                        .push(
                            Router::with_path("refresh")
                                .post(handlers::auth::refresh_token),
                        ),
                )
                .push(
                    Router::with_path("courses")
                        .get(handlers::course::list_courses)
                        .post(handlers::course::create_course)
                        .push(
                            Router::with_path("{id}")
                                .get(handlers::course::get_course)
                                .put(handlers::course::update_course)
                                .delete(handlers::course::delete_course),
                        ),
                )
                .push(
                    Router::with_path("challenges")
                        .get(handlers::challenge::list_challenges)
                        .post(handlers::challenge::create_challenge)
                        .push(
                            Router::with_path("{id}")
                                .get(handlers::challenge::get_challenge)
                                .put(handlers::challenge::update_challenge)
                                .delete(handlers::challenge::delete_challenge),
                        ),
                )
                .push(
                    Router::with_path("users")
                        .get(handlers::user::list_users)
                        .push(
                            Router::with_path("{id}")
                                .get(handlers::user::get_user)
                                .put(handlers::user::update_user),
                        ),
                ),
        )
        .push(
            Router::with_path("{**path}")
                .all(handlers::not_found),
        )
}
